Algoritmo "circulo"
// Descrição   : exercícios estruturas sequênciais
// Curso Udemy : algoritmo e lógica de programação
// Data atual  : 30/10/2021
Var
//variáveis
    raio, area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("Digite o valor do raio do círculo: ")
    leia(raio)

    area <- Pi * Exp(raio, 2)
    
    escreva("Area = ", area:8:3)
Fimalgoritmo