Algoritmo "exemplo3-aula23"

// Descrição   : Como fazer uma expressão aritmética com duas oerações

Var

//quando tem variáveis do mesmo tipo, pode-se declarar da seguinte forma:
   b1, b2, h, area : real

Inicio
// atribuindo valores ás variáveis
   b1 <- 6.0
   b2 <- 8.0
   h <- 5.0
   
//cálculando a área da figura
   area <- (b1 + b2) / 2.0 * h;

// printando o resultado do cálculo para o usuário
   escreval(area)

Fimalgoritmo