Algoritmo "soma"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/10/2021
Var
//variáveis
x, y, soma : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor de X:")
leia(x)
escreva("Digite o valor de Y:")
leia(y)

soma <- x + y

escreva("Soma de x e y:", soma:8:2)

Fimalgoritmo