Algoritmo "teste_saida2"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/10/2021
Var
// Seção de Declarações das variáveis 
   idade : inteiro
   salario : real
   nome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   idade <- 32
   salario <- 4560.9
   nome <- "Maria Silva"
   escreva("A funcionaria ", nome, " ganha ", salario:8:2, " e tem", idade, " anos.")

Fimalgoritmo